import 'dart:async';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'app.dart';
import 'core/api/api_client.dart';
import 'core/env.dart';
import 'core/time.dart';
import 'firebase_options.dart';
import 'features/notifications/fcm_service.dart';
import 'features/payments/payments_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Must run before any appointment/slot time is parsed — those render in
  // Ohio time regardless of the device's timezone (see core/time.dart).
  initBusinessTime();

  await Supabase.initialize(
    url: Env.supabaseUrl,
    // supabase_flutter 2.16 renamed `anonKey` -> `publishableKey`; legacy
    // anon keys (including the local-dev demo key) are accepted here.
    publishableKey: Env.supabaseAnonKey,
  );

  // A container we control so FCM can navigate via routerProvider.
  final container = ProviderContainer();

  // Configure Stripe with the compile-time key immediately (fast + offline
  // safe), then refresh from the server in the background. The server key wins,
  // so a Stripe test↔live switch can be flipped server-side (env + redeploy)
  // without shipping a new app build. Non-blocking: startup never waits on it.
  await const PaymentsService().init();
  unawaited(_refreshStripeConfig(container));

  await _initFirebase(container);

  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const PikavoltApp(),
    ),
  );
}

/// Fetches the server-resolved Stripe publishable key and re-applies it, so a
/// test↔live switch done on the server (env + redeploy) takes effect on the
/// app's next launch — no new build. Best-effort with a timeout: any failure
/// leaves the compile-time key in place. Runs unawaited so it never blocks
/// startup or the payment screens (which are several network-bound steps away).
Future<void> _refreshStripeConfig(ProviderContainer container) async {
  try {
    final key = await container
        .read(apiClientProvider)
        .getStripePublishableKey()
        .timeout(const Duration(seconds: 8));
    if (key != null) {
      await const PaymentsService().init(serverPublishableKey: key);
    }
  } catch (e) {
    debugPrint('Stripe config refresh failed (using build-time key): $e');
  }
}

/// Guarded Firebase init. Config was generated by `flutterfire configure`
/// (lib/firebase_options.dart + native google-services.json /
/// GoogleService-Info.plist), so this runs by default. Still guarded: push is
/// non-essential, and iOS token retrieval fails until an APNs key is uploaded
/// to Firebase — the app must keep working regardless.
///
/// Set --dart-define=HAS_FIREBASE_CONFIG=false to force-skip (e.g. tests).
Future<void> _initFirebase(ProviderContainer container) async {
  if (!Env.hasFirebaseConfig) {
    debugPrint('Firebase init skipped (HAS_FIREBASE_CONFIG=false).');
    return;
  }
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint('Firebase init failed (continuing without push): $e');
    return;
  }
  // FCM setup (permission + token registration) is fire-and-forget: it must
  // never block startup. On an iOS simulator without an APNs key, getToken()
  // can hang, which would otherwise freeze the app before runApp(). The service
  // logs and swallows its own errors.
  unawaited(container.read(fcmServiceProvider).init());
}
