import 'dart:async';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'app.dart';
import 'core/env.dart';
import 'core/time.dart';
import 'firebase_options.dart';
import 'features/notifications/fcm_service.dart';
import 'features/payments/payments_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Must run before any appointment/slot time is parsed — those render in
  // Ohio time regardless of the device's timezone (see core/time.dart).
  initBusinessTime();

  await Supabase.initialize(
    url: Env.supabaseUrl,
    // supabase_flutter 2.16 renamed `anonKey` -> `publishableKey`; legacy
    // anon keys (including the local-dev demo key) are accepted here.
    publishableKey: Env.supabaseAnonKey,
  );

  // Stripe publishable key (no-op without STRIPE_PUBLISHABLE_KEY dart-define).
  await const PaymentsService().init();

  // A container we control so FCM can navigate via routerProvider.
  final container = ProviderContainer();

  await _initFirebase(container);

  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const PikavoltApp(),
    ),
  );
}

/// Guarded Firebase init. Config was generated by `flutterfire configure`
/// (lib/firebase_options.dart + native google-services.json /
/// GoogleService-Info.plist), so this runs by default. Still guarded: push is
/// non-essential, and iOS token retrieval fails until an APNs key is uploaded
/// to Firebase — the app must keep working regardless.
///
/// Set --dart-define=HAS_FIREBASE_CONFIG=false to force-skip (e.g. tests).
Future<void> _initFirebase(ProviderContainer container) async {
  if (!Env.hasFirebaseConfig) {
    debugPrint('Firebase init skipped (HAS_FIREBASE_CONFIG=false).');
    return;
  }
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint('Firebase init failed (continuing without push): $e');
    return;
  }
  // FCM setup (permission + token registration) is fire-and-forget: it must
  // never block startup. On an iOS simulator without an APNs key, getToken()
  // can hang, which would otherwise freeze the app before runApp(). The service
  // logs and swallows its own errors.
  unawaited(container.read(fcmServiceProvider).init());
}
