/**
 * Service categories — static marketing copy derived from
 * docs/owner-content.md (source of truth). The db seed mirrors this; feature
 * agents will replace static usage with db-backed data where appropriate.
 */
export interface ServiceCategory {
  slug: string;
  name: string;
  blurb: string;
  items: string[];
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    slug: 'residential',
    name: 'Residential Electric Service',
    blurb: 'Upgrades, wiring, lighting, EV chargers, and generators for your home.',
    items: [
      'Electrical Service Upgrades',
      'Panel Replacement & Upgrades',
      'New Home Wiring',
      'Home Additions',
      'Whole Home Rewiring',
      'Electrical Remodeling',
      'Troubleshooting & Repairs',
      'Breaker Replacement',
      'Circuit Installation',
      'Dedicated Circuits',
      'GFCI & AFCI Protection',
      'Outlet Installation & Replacement',
      'USB Outlets',
      'Smart Switches & Dimmers',
      'Light Fixture Installation',
      'Chandelier Installation',
      'Recessed Lighting',
      'LED Lighting Upgrades',
      'Ceiling Fan Installation',
      'Bathroom Exhaust Fans',
      'Smoke & Carbon Monoxide Detectors',
      'Whole-Home Surge Protection',
      'Hot Tub & Spa Wiring',
      'Pool Equipment Wiring',
      'EV Charger Installation',
      'Generator Installation',
      'Transfer Switch Installation',
      'Appliance Wiring',
      'Dryer & Range Circuits',
      'Well Pump Wiring',
      'Septic System Wiring',
      'Garage & Workshop Wiring',
      'Outdoor Lighting',
      'Landscape Lighting',
      'Security Lighting',
      'Flood Lights',
      'Motion Sensor Lighting',
      'Electrical Inspections',
    ],
  },
  {
    slug: 'commercial',
    name: 'Commercial Service',
    blurb: 'Build-outs, three-phase power, lighting retrofits, and maintenance for businesses.',
    items: [
      'New Commercial Construction',
      'Tenant Build-Outs',
      'Office Wiring',
      'Retail Electrical',
      'Restaurant Electrical',
      'Commercial Panel Installation',
      'Commercial Service Upgrades',
      'Three-Phase Power',
      'Dedicated Equipment Circuits',
      'LED Lighting Retrofits',
      'Parking Lot Lighting',
      'Pole Lighting',
      'Exit & Emergency Lighting',
      'Occupancy Sensors',
      'Time Clocks',
      'Lighting Controls',
      'Electrical Maintenance',
      'Troubleshooting',
      'Equipment Connections',
      'Commercial Generator Installation',
    ],
  },
  {
    slug: 'agricultural',
    name: 'Agricultural & Farm Electrical',
    blurb: 'Barn wiring, arena lighting, grain bins, and farm power distribution.',
    items: [
      'Barn Wiring',
      'Horse Barn Electrical',
      'Pole Barn Electrical',
      'Livestock Facility Wiring',
      'Arena Lighting',
      'Stable Lighting',
      'Well Pumps',
      'Grain Bin Electrical',
      'Farm Equipment Power',
      'Feed Building Wiring',
      'Fence Charger Circuits',
      'Outdoor Receptacles',
      'Security Lighting',
      'Generator Connections',
      'New Farm Services',
      'Underground Farm Power Distribution',
    ],
  },
  {
    slug: 'repair-maintenance',
    name: 'Repair & Maintenance',
    blurb: 'Emergency repairs, troubleshooting, code corrections, and preventative care.',
    items: [
      'Emergency Electrical Repairs',
      'Troubleshooting',
      'Breaker Problems',
      'Flickering Lights',
      'Power Loss Diagnosis',
      'Outlet Repairs',
      'Switch Repairs',
      'Code Corrections',
      'Insurance Repairs',
      'Storm Damage Repairs',
      'Preventative Maintenance',
    ],
  },
  {
    slug: 'specialty',
    name: 'Specialty Services',
    blurb: 'EV charging, standby generators, smart home wiring, and low-voltage work.',
    items: [
      'EV Charging Stations',
      'Standby Generators',
      'Whole-House Surge Protection',
      'Smart Home Wiring',
      'Camera System Power',
      'Doorbell Wiring',
      'Landscape Lighting',
      'Accent Lighting',
      'Holiday Lighting Power',
      'Sign Power',
      'Data & Low-Voltage Conduit',
      'Equipment Disconnects',
    ],
  },
  {
    slug: 'underground-site-work',
    name: 'Underground & Site Work',
    blurb: 'Trenching, conduit systems, underground feeders, and site restoration.',
    items: [
      'Electrical Trenching',
      'Underground Power Installation',
      'Conduit Installation',
      'PVC & HDPE Conduit Systems',
      'Underground Feeders',
      'Secondary Electrical Services',
      'Meter-to-Building Feeds',
      'Garage Feeds',
      'Barn Feeds',
      'Detached Building Power',
      'Transformer Connections',
      'Site Lighting Circuits',
      'Pull Box Installation',
      'Handhole Installation',
      'Backfilling & Site Restoration',
    ],
  },
  {
    slug: 'service-utility-work',
    name: 'Service & Utility Work',
    blurb: 'Meter sockets, service masts, utility coordination, and temporary power.',
    items: [
      'Meter Socket Replacement',
      'Meter Bank Replacement',
      'CT Cabinet Installation',
      'Utility Coordination',
      'Overhead Service Installation',
      'Underground Service Installation',
      'Temporary Power',
      'Disconnect Installation',
      'Main Breaker Replacement',
      'Service Mast Replacement',
      'Weather Head Replacement',
      'Service Entrance Cable Replacement',
    ],
  },
];

export function getServiceCategory(slug: string): ServiceCategory | undefined {
  return SERVICE_CATEGORIES.find((c) => c.slug === slug);
}
